In [1]:
import torch

# Criando um tensor original
original_tensor = torch.tensor([[1, 2], [3, 4]])

# Clonando o tensor original
cloned_tensor = original_tensor.clone()

# Modificando o tensor clonado
cloned_tensor[0, 0] = 100

print(original_tensor)
print(cloned_tensor)


tensor([[1, 2],
        [3, 4]])
tensor([[100,   2],
        [  3,   4]])


In [4]:
import torch

# Criando um tensor de 1 dimensão
tensor = torch.arange(12)

# Reformatando o tensor para ter 3 dimensões
reshaped_tensor = tensor.reshape(2, 3, -1)

print(tensor)
print(reshaped_tensor)


tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]]])
